### ISSUE TITLE
PKPD graph TimePoint (h) axis in log format

### ISSUE THREAD

**Issue by flawmop** [CardiacModelling/ap-nimbus-client#101]
As mentioned in https://cardiac-modelling.slack.com/archives/DKUA91H29/p1683140113202649, to the inexperienced eye (i.e. mine) it doesn't look right to have the display of PKPD - APD90 vs. TimePoint results showing the TimePoint (h) on a log scale.

**Comment by MauriceHendrix** [comment]
that link doesn't work for me

**Comment by flawmop** [comment]
It's when you supply some PKPD input to the simulation.

**Comment by mirams** [comment]
Yeah, time shouldn't ever be on a log axis.

**Comment by MauriceHendrix** [comment]
@flawmop have you got the tsv file you used for that example? & what model & other settings?

**Comment by MauriceHendrix** [comment]
![image](https://github.com/CardiacModelling/ap-nimbus-client/assets/52317399/b08a25f6-09a6-452b-b6ad-87ab372db201)
Is that waht you were expecting? If soo see #104

**Comment by flawmop** [comment]
That certainly looks better.
It looks like it's not possible to toggle individual concentration plots unfortunately (so in that plot you've shown it's not clear where concentrations 1 and 2 are hiding, but we can add that as a enhancement issue). Which model/blocks was that?

**Comment by MauriceHendrix** [comment]
O'Hara-Rudy CiPA with all the default settings and your PKPD file

**Comment by flawmop** [comment]
Resolved by https://github.com/CardiacModelling/ap-nimbus-client/pull/104
