### ISSUE TITLE
Django authn mechanism issues

### ISSUE THREAD

**Issue by flawmop** [CardiacModelling/ap-nimbus-client#115]
Things seems to be a bit unreliable with the Django authentication system

- If a password is reset using the "Reset Password" via email option, then the password is accepted only until the `ap-nimbus-client` container is restarted.
- If a user's email is updated using the `accounts/myaccount/` facility, they can't log in again until they've reset their password.

**Comment by MauriceHendrix** [comment]
at least the password reset does otherwise work, so at least people aren't logged out completely.

**Comment by flawmop** [comment]
@MauriceHendrix , are you going to be able to fix this before you disappear? It's the only "bug" issue left I think, all the other stuff is enhancements, so it'd be great to have it resolved - plus reviewing any changes would be a good intro for me into the Django security.

**Comment by MauriceHendrix** [comment]
to be honest I have no idea where to start. I have search but haven't found anything similar. If it was just always doing it I might have some ideas, but the fact that original not reset passwords don't do this baffels me. The password reset is just an official django add-on, that I didn't write.

**Comment by MauriceHendrix** [comment]
actually it's not even really an add-on.
https://docs.djangoproject.com/en/4.2/topics/auth/default/

**Comment by mirams** [comment]
If we have a minimal working example, maybe we should put a question on stackoverflow if we think we aren't doing it right, or an issue on Django's issue tracker if we think it is a bug?!

**Comment by MauriceHendrix** [comment]
@gef I think I have a solution.
I restarted Tried it with a new account and it seemed to survive removing and redeploying the client docker container.
Check that you can still log in? If not, do a reset and I'll once again do a redeply so we can see if it helps.
What I did is add `ProxyPreserveHost On` to teh apache config as suggested in:
https://stackoverflow.com/questions/51087547/how-to-correctly-configure-apache-for-reverse-proxy-serve-django-app
