### ISSUE TITLE
AP-nimbus (cloudified AP Predict) architecture

### ISSUE THREAD

**Issue by MauriceHendrix** [CardiacModelling/ap-nimbus-client#7]
This issue is to document the architecture of AP-nimbus (cloudified AP Predict). At the moment it is as follows. 
![image](https://user-images.githubusercontent.com/52317399/145575053-6754ac15-0e7a-4fab-a6d1-6451284d0380.png)
However we are planning
- to pull out the NGINX into it's own component (perhaps also removing apache, not ot forget about lookup tables)
- possibly to introduce a load balancer allowing multiple AP predict instanes

**Comment by flawmop** [comment]
This seems to be completed, so closing.
